# Generated by Django 3.0.8 on 2020-07-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200716_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
