# Generated by Django 3.0.8 on 2020-07-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200709_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel',
            name='fee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
