# Generated by Django 3.0.8 on 2020-07-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200710_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel',
            name='time',
            field=models.CharField(max_length=10),
        ),
    ]
